################# 日志 ################
log:
  level: info           
  file: ./mosdns.log    

  ################# 必要插件 ################
plugin:
  - tag: main_server                
    type: server                    
    args:                           
      entry: main_sequence         
      max_concurrent_queries: 0     
      server:                       
        - protocol: udp             
          addr: 0.0.0.0:53          
          timeout: 5                
        - protocol: tcp
          addr: 0.0.0.0:53
          timeout: 5
          idle_timeout: 10          

################# 可执行插件 ################

  - tag: main_sequence      
    type: sequence          
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_direct           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_clash             # 用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。以下是"顺序 IP 分流"的逻辑。很稳定，不易出错。
        # <高级> 如果想用"并发 IP 分流"逻辑，从下文的 <并发 IP 分流示例> 里选择一个方案，
        # 然后将下面几行替换掉。
        - forward_direct               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果(本地)应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_clash               # 否则去请求远程服务器的结果

################ 解析服务器插件 #################
  
##### 解析直连域名的插件，direct #####

  - tag: forward_direct
    type: fast_forward                   
    args:    
      upstream:     
        - addr: 119.29.29.29
          trusted: true
          idle_timeout: 30
          max_conns: 5
        - addr: 223.6.6.6
          trusted: true
          idle_timeout: 30
          max_conns: 5
        - addr: 114.114.114.114
          trusted: true
          idle_timeout: 30
          max_conns: 5          
      timeout: 2
      
##### 解析代理域名的插件，clash #####
  - tag: forward_clash
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:5352
          trusted: true
      
################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
        
include: [ ]

